#cloud-config

timezone: Europe/London
fqdn: NAME.djm.me

write_files:
  - path: /etc/netplan/80-static-ip.yaml
    content: |
      network:
        version: 2
        ethernets:
          eth1:
            addresses: ADDRESSES

users:
  - name: dave
    shell: /bin/bash
    ssh-authorized-keys:
      - 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGRzRUvx7ESGxsXrmNKgVY+pg8uc1ZHxzqVoMVznlzWF d@djm.me'
    sudo:
      - 'ALL=(ALL) NOPASSWD:ALL'

runcmd:
  - netplan apply
  - mkdir /home/dave/.dotfiles
  - chown dave:dave /home/dave/.dotfiles
  - echo '[[ ! -d .git ]] && cd && wget https://djm.me/dot && source dot' >> /home/dave/.bashrc

# vim:ts=2 sts=2 sw=2
