#!/usr/bin/env bash
set -euo pipefail

# To test this repeatedly:
#   sudo pkill -u dave; sudo userdel dave; sudo rm -rf /home/dave; setup dave && ssh dave@localhost
# Or (in Docker):
#   sudo pkill -u dave; sudo userdel dave; sudo rm -rf /home/dave; setup dave && sudo -su dave

# Must be run as root
# Note: We can't use anything in $PATH because of this (e.g. 'is-root-user')
if [[ $UID -ne 0 ]]; then
    exec sudo --preserve-env=SSH_AUTH_SOCK "$0" "$@"
fi

# Can't use $HOME here or assume it is in the path
source "$(dirname "$0")/../../.bash/style"

# Create user
style lcyan,bold  'Creating user...'
useradd \
    --comment "Dave James Miller" \
    --create-home \
    --groups adm,sudo,www-data \
    --shell /bin/bash \
    --user-group \
    dave

# Copy SSH key
style lcyan,bold  'Installing SSH key...'
umask 077
mkdir ~dave/.ssh
ssh-add -L >> ~dave/.ssh/authorized_keys
chown dave:dave ~dave/.ssh ~dave/.ssh/authorized_keys

# Prepare dotfiles
style lcyan,bold  'Preparing dotfiles installer...'
echo '[[ ! -d .git ]] && cd && wget https://djm.me/dot && source dot' >> ~dave/.bashrc
chown dave:dave ~dave/.bashrc

# Prompt for a password
style lcyan,bold  'Setting password...'
passwd dave

# Done
style lcyan,bold  'Done.'
