#!/usr/bin/env bash
set -euo pipefail

added_to_group=false
exe=$(basename "$0")
revert=false

main() {
    parse-arguments "$@"

    if $revert; then
        uninstall-docker
        uninstall-lazy-docker
        uninstall-dive
        remove-docker-repository
    else
        add-docker-repository
        install-docker
        install-lazy-docker
        install-dive
    fi

    finished
}

help() {
    echo "Usage: $exe [options]"
    echo
    echo "Install Docker, Lazy Docker and Dive."
    echo
    echo "Options:"
    echo "  -h, --help      display this help"
    echo "  -r, --revert    uninstall everything"
}

parse-arguments() {
    local args
    args=$(getopt -n "$exe" -o 'hr' -l 'help,insecure-group,revert' -- "$@")
    eval set -- "$args"

    while true; do
        case "$1" in
            -h | --help)    help; exit ;;
            -r | --revert)  revert=true; shift ;;
            --)             shift; break ;;
        esac
    done
}

# Using the upstream repository because (1) Docker 27 enables IPv6 support by
# default, which is much simpler than configuring it manually, and (2) it
# ensures consistency between Debian and Ubuntu hosts
add-docker-repository() {
    style lcyan,bold 'Adding Docker repository...'
    maybe-sudo curl -fsSL "https://download.docker.com/linux/$(os-id)/gpg" -o /etc/apt/keyrings/docker.asc

    echo "deb [arch=$(os-arch) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/$(os-id) $(os-codename) stable" |
        sudo-write /etc/apt/sources.list.d/docker.list

    maybe-sudo apt update
    echo
}

remove-docker-repository() {
    style lcyan,bold 'Removing Docker repository...'
    maybe-sudo rm -f /etc/apt/keyrings/docker.asc /etc/apt/sources.list.d/docker.list
    echo
}

packages() {
    # https://docs.docker.com/engine/install/debian/
    echo docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
}

install-docker() {
    style lcyan,bold 'Installing Docker...'
    maybe-sudo apt install -y $(packages)
    echo
}

uninstall-docker() {
    style lcyan,bold 'Uninstalling Docker...'
    maybe-sudo apt purge --auto-remove $(packages)
    echo
}

check-for-homebrew() {
    if ! is-executable brew; then
        style lred "Homebrew is not installed (run 'setup brew' to install it)"
        return 1
    fi
}

install-lazy-docker() {
    style lcyan,bold 'Installing Lazy Docker...'
    if check-for-homebrew; then
        # https://github.com/jesseduffield/lazydocker
        brew install jesseduffield/lazydocker/lazydocker
    fi
    echo
}

uninstall-lazy-docker() {
    style lcyan,bold 'Uninstalling Lazy Docker...'
    if check-for-homebrew; then
        brew uninstall jesseduffield/lazydocker/lazydocker || true
    fi
    echo
}

install-dive() {
    style lcyan,bold 'Installing Dive...'
    if check-for-homebrew; then
        brew install dive
    fi
    echo
}

uninstall-dive() {
    style lcyan,bold 'Uninstalling Dive...'
    if check-for-homebrew; then
        brew uninstall dive || true
    fi
    echo
}

finished() {
    style lcyan,bold 'Done.'

    if $added_to_group && ! is-in-group docker; then
        echo
        echo 'You may need to log out and back in to refresh your groups, or run:'
        # shellcheck disable=SC2016
        echo '  exec sudo su -l "$USER"'
    fi
}

main "$@"
