#!/usr/bin/env bash
set -euo pipefail

sudo apt install -y fail2ban ufw

sudo ufw default reject incoming # Default is 'deny'
sudo ufw allow ssh
sudo ufw allow http
sudo ufw allow https
sudo ufw enable
sudo ufw status verbose
