#!/usr/bin/env bash
set -euo pipefail

# Parse arguments
exe=$(basename "$0")

help() {
    echo "Usage: $exe [options]"
    echo
    echo "Install/upgrade git-filter-repo."
    echo
    echo "Options:"
    echo "  -h, --help      display this help"
    echo "  -r, --revert    uninstall git-filter-repo"
}

args=$(getopt -n "$exe" -o 'hr' -l 'help,revert' -- "$@")
eval set -- "$args"

revert=false

while true; do
    case "$1" in
        -h | --help)    help; exit ;;
        -r | --revert)  revert=true; shift ;;
        --)             shift; break ;;
    esac
done

# Install/uninstall PsySH
if $revert; then
    rm -fv ~/.bin/local/git-filter-repo
else
    curl -fsS 'https://raw.githubusercontent.com/newren/git-filter-repo/main/git-filter-repo' > ~/.bin/local/git-filter-repo
    chmod +x ~/.bin/local/git-filter-repo
fi
