#!/usr/bin/env bash
set -euo pipefail

# Install dependencies
# (Chromium installed to allow activation via browser)
sudo apt install -y \
    chromium-browser \
    default-jre \
    fonts-firacode \
    libgbm-dev \
    libgdm-dev \
    openjfx

# Install PhpStorm
sudo snap install --classic phpstorm
