#!/usr/bin/env bash
set -euo pipefail

ID=''
if [[ -f /etc/os-release ]]; then
    source /etc/os-release
fi

# Chromium is required to allow activation via browser
chromium='chromium'
if [[ $ID = 'ubuntu' ]]; then
    chromium='chromium-browser'
fi

# Install dependencies
sudo apt install -y \
    "$chromium" \
    default-jre \
    fonts-firacode \
    libgbm-dev \
    libgdm-dev \
    openjfx \
    snapd

# Install PhpStorm
sudo snap install --classic phpstorm
