#!/usr/bin/env bash
set -euo pipefail

# Chromium is required to allow activation via browser
if is-ubuntu; then
    chromium='chromium-browser'
else
    chromium='chromium'
fi

# Install dependencies
sudo apt install -y \
    "$chromium" \
    default-jre \
    fonts-firacode \
    libgbm-dev \
    libgdm-dev \
    openjfx \
    snapd

# Install PhpStorm
sudo snap install --classic phpstorm
