#!/usr/bin/env bash
set -euo pipefail

if [[ -f /etc/samba/smb.conf ]]; then
    echo 'Samba is already configured' >&2
    exit 1
fi

sudo apt install -y samba

sudo-write -a /etc/samba/smb.conf <<END

[homes]
browseable = no
read only = no

[local]
path = /local
read only = no
create mask = 664
directory mask = 775
END

sudo systemctl reload smbd
sudo smbpasswd -a $USER
