#!/usr/bin/env bash
set -euo pipefail

size_gb=${1-}

if [[ -z $size_gb ]]; then
    echo "Usage: $(basename "$0") <SIZE_IN_GiB>"
    echo
    if [[ -f /swap.img ]]; then
        current_size=$(stat -c %s /swap.img)
        echo "The swap file is currently $((current_size / 1024 / 1024 / 1024)) GiB"
        echo "The new size may be 0 to remove it"
    else
        echo "The swap file doesn't currently exist"
    fi
    exit
fi

if [[ -f /swap.img ]]; then
    echo "Removing /swap.img..."
    sudo sed -i.bak '/^\/swap\.img\b/d' /etc/fstab
    sudo swapoff /swap.img
    sudo rm -f /swap.img
    echo
fi

if [[ $size_gb -gt 0 ]]; then
    echo "Creating /swap.img (${size_gb} GiB)..."
    size_mb=$(($size_gb * 1024))
    sudo dd if=/dev/zero of=/swap.img bs=1MiB count=$size_mb
    sudo chmod 600 /swap.img
    sudo mkswap /swap.img
    sudo swapon /swap.img
    echo '/swap.img none swap sw 0 0' | sudo-write -a /etc/fstab
    echo
fi

echo 'Done.'
