#!/usr/bin/env bash
set -euo pipefail

user='test'

# Delete existing account
if grep -q "^$user:" /etc/passwd; then
        if ask 'Delete and recreate the account?' N; then
        echo "Deleting $user user..."
        echo
        sudo pkill -u "$user" && sleep 1
        sudo deluser --remove-home "$user"
    fi
fi

# Create new account
if ! grep -q "^$user:" /etc/passwd; then

    echo
    echo "Recreating $user user..."
    sudo useradd --create-home --skel=/etc/skel --shell=/bin/bash "$user"

    if grep -q "^docker:" /etc/group; then
        sudo usermod -aG docker "$user"
    fi

    # Setup SSH key, so I can use SSH to connect without a password, and so SSH
    # agent forwarding still works (unlike when using sudo)
    sudo mkdir "/home/$user/.ssh"
    ssh-add -L | sudo-write "/home/$user/.ssh/authorized_keys"
    sudo chown "$user:$user" -R "/home/$user/.ssh"
    sudo chmod go-rwx -R "/home/$user/.ssh"

    # Automatically download and run the Dotfiles installation script
    # Use '-n' ("no dotfiles") to disable this step
    if [[ ${1-} != '-n' ]]; then
        # Also delete 'dot' and '.git' if they already exist, in case it fails the first time
        sudo su "$user" -c "echo 'cd; rm -rf .git dot; wget djm.me/dot && . dot' >> ~/.bashrc"
    fi

fi

# Switch to the test user account
echo
ssh "$user@localhost"
