#!/usr/bin/env php
<?php

$HOME = $_SERVER['HOME'];

if ($argc !== 3) {
    $name = basename(__FILE__);
    echo "Usage: $name <ui-font-size> <code-font-size>";
}

[, $uiFontSize, $codeFontSize] = $argv;

foreach (glob("$HOME/.config/JetBrains/*/options/other.xml") as $file) {
    $xml = simplexml_load_file($file);

    $uiSettings = $xml->xpath('component[@name="NotRoamableUiSettings"]')[0] ?? null;
    if (!$uiSettings) {
        $uiSettings = $xml->addChild('component');
        $uiSettings['name'] = 'NotRoamableUiSettings';
    }

    $fontSize = $uiSettings->xpath('option[@name="fontSize"]')[0] ?? null;
    if (!$fontSize) {
        $fontSize = $uiSettings->addChild('option');
        $fontSize['name'] = 'fontSize';
    }

    $fontSize['value'] = $uiFontSize;

    $node = $xml->xpath('component[@name="PropertyService"]')[0] ?? null;
    if (!$node) {
        $node = $xml->addChild('component', '{}');
        $node['name'] = 'PropertyService';
    }

    $json = json_decode((string)$node, true);
    $json['keyToString']['fontSizeToResetConsole'] = "$codeFontSize.0";
    $json['keyToString']['fontSizeToResetEditor'] = "$codeFontSize.0";
    $node[0] = json_encode($json, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);

    $xml->saveXML($file);
}

foreach (glob("$HOME/.config/JetBrains/*/options/editor-font.xml") as $file) {
    $xml = simplexml_load_file($file);

    $defaultFont = $xml->xpath('component[@name="DefaultFont"]')[0] ?? null;
    if (!$defaultFont) {
        $defaultFont = $xml->addChild('component');
        $defaultFont['name'] = 'DefaultFont';
    }

    $fontSize = $defaultFont->xpath('option[@name="FONT_SIZE"]')[0] ?? null;
    if (!$fontSize) {
        $fontSize = $defaultFont->addChild('option');
        $fontSize['name'] = 'FONT_SIZE';
    }
    $fontSize['value'] = $codeFontSize;

    $fontSize2D = $defaultFont->xpath('option[@name="FONT_SIZE_2D"]')[0] ?? null;
    if (!$fontSize2D) {
        $fontSize2D = $defaultFont->addChild('option');
        $fontSize2D['name'] = 'FONT_SIZE_2D';
    }
    $fontSize2D['value'] = "$codeFontSize.0";

    $xml->saveXML($file);
}
