#!/usr/bin/env bash
set -euo pipefail

if ! dir=$(findup -f artisan -o -f bin/artisan); then
    echo "You do not appear to be within a Laravel directory" >&2
    exit 1
fi

cd "$dir"

# Shim to support multiple PHP versions or Docker
if [[ -x bin/artisan ]]; then
    exec bin/artisan "$@"
fi

if [[ -x bin/php ]]; then
    exec bin/php artisan "$@"
fi

exec php artisan "$@"
