#!/usr/bin/env bash
set -o errexit -o nounset -o pipefail

prompt=${1:-}

if [[ -z $prompt ]]; then
    echo "usage: $(basename "$0") <prompt> [default]" >&2
    exit 2
fi

while true; do

    if [[ ${2:-} = 'Y' ]]; then
        default='Y'
        yn='Y/n'
    elif [[ ${2:-} = 'N' ]]; then
        default='N'
        yn='y/N'
    else
        default=''
        yn='y/n'
    fi

    # Ask the question (not using "read -p" as it uses stderr not stdout)
    echo -n "$prompt [$yn] "

    # Read the answer (use /dev/tty in case stdin is redirected from somewhere else)
    read reply </dev/tty

    # Default?
    if [[ -z $reply ]]; then
        reply=$default
    fi

    # Check if the reply is valid
    case "$reply" in
        Y*|y*) exit 0 ;;
        N*|n*) exit 1 ;;
    esac

done
