#!/usr/bin/env bash
set -o errexit -o nounset -o pipefail

# https://github.com/sharkdp/bat#on-ubuntu-using-apt
if is-executable batcat; then
    exec batcat --style=plain "$@"
fi

if is-executable bat; then
    exec bat --style=plain "$@"
fi

exec cat "$@"
