#!/bin/bash
set -o errexit -o nounset -o pipefail

repo=${1:-}
shift

if [[ -z $repo ]]; then
    echo 'Usage: clone <name> [target]' >&2
    exit 2
fi

if [[ $repo == *@* ]] || [[ $repo == *:* ]] || [[ $repo == /* ]] || [[ $repo == *..* ]]; then
    : # No change
elif [[ $repo == */* ]]; then
    repo="git@github.com:$repo.git"
else
    repo="git@github.com:d13r/$repo.git"
fi

source "$HOME/.bash/color.bash"

color lblue "$repo"
exec git clone "$repo" "$@"
