#!/usr/bin/env bash
set -euo pipefail

repo=${1:-}
shift

if [[ -z $repo ]]; then
    echo 'Usage: clone <name> [target]' >&2
    exit 2
fi

if [[ $repo == *@* ]] || [[ $repo == *:* ]] || [[ $repo == /* ]] || [[ $repo == *..* ]]; then
    : # No change
elif [[ $repo == drupal/* && $repo != drupal/core && $repo != drupal/recommended-project ]]; then
    repo="https://git.drupalcode.org/project/${repo#drupal/}.git"
elif [[ $repo == it/* ]]; then
    repo="git@git.maths.ox.ac.uk:$repo.git"
elif [[ $repo == */* ]]; then
    repo="git@github.com:$repo.git"
else
    repo="git@github.com:d13r/$repo.git"
fi

style lblue "$repo"
exec git clone "$repo" "$@"
