#!/bin/bash
set -o errexit -o nounset -o pipefail

repo="${1:-}"

if [[ -z $repo ]]; then
    echo 'Usage: clone <name>' >&2
    exit 2
fi

if [[ $repo == *@* ]] || [[ $repo == *:* ]] || [[ $repo == */*/* ]]; then
    exec git clone "$repo"
fi

if [[ $repo == */* ]]; then
    exec git clone "git@djm.me:$repo.git"
fi

exec git clone "git@djm.me:dave/$repo.git"
