#!/bin/bash
set -o nounset -o pipefail -o errexit

# To test this repeatedly:
# sudo pkill -u dave; sudo userdel dave; sudo rm -rf /home/dave; create-dave-user && ssh dave@localhost

# Must be run as root
if [ $UID -ne 0 ]; then
    exec sudo "$0" "$@"
fi

source ~/.bash/color.bash

# Create user
color lgreen 'Creating user...'
useradd \
    --comment "$(git config --get user.name)" \
    --create-home \
    --groups adm,sudo,www-data \
    --shell /bin/bash \
    --user-group \
    dave

# Copy SSH key
color lgreen 'Installing SSH key...'
umask 077
mkdir ~dave/.ssh
ssh-add -L >> ~dave/.ssh/authorized_keys
chown dave:dave ~dave/.ssh ~dave/.ssh/authorized_keys

# Prepare dotfiles
color lgreen 'Preparing dotfiles...'
echo '[ ! -d .git ] && cd && wget https://djm.me/cfg && source cfg' >> ~dave/.bashrc
chown dave:dave ~dave/.bashrc

# Prompt for a password
passwd dave

# Done
color lgreen 'Done.'
