#!/usr/bin/env bash
set -o errexit -o nounset -o pipefail

# To test this repeatedly:
#   sudo pkill -u dave; sudo userdel dave; sudo rm -rf /home/dave; create-dave-user && ssh dave@localhost
# Or (in Docker):
#   sudo pkill -u dave; sudo userdel dave; sudo rm -rf /home/dave; create-dave-user && sudo -su dave

# Must be run as root
if ! is-root-user; then
    exec sudo --preserve-env=SSH_AUTH_SOCK "$0" "$@"
fi

# Can't use $HOME here or assume it is in the path
source "$(dirname "$0")/../.bash/style"

# Create user
style lcyan,bold  'Creating user...'
useradd \
    --comment "Dave James Miller" \
    --create-home \
    --groups adm,sudo,www-data \
    --shell /bin/bash \
    --user-group \
    dave

# Copy SSH key
style lcyan,bold  'Installing SSH key...'
umask 077
mkdir ~dave/.ssh
ssh-add -L >> ~dave/.ssh/authorized_keys
chown dave:dave ~dave/.ssh ~dave/.ssh/authorized_keys

# Prepare dotfiles
style lcyan,bold  'Preparing dotfiles installer...'
echo '[[ ! -d .git ]] && cd && wget https://djm.me/cfg && source cfg' >> ~dave/.bashrc
chown dave:dave ~dave/.bashrc

# Prompt for a password
style lcyan,bold  'Setting password...'
passwd dave

# Done
style lcyan,bold  'Done.'
