#!/usr/bin/env bash
set -o errexit -o nounset -o pipefail

exe=bin/cypress
if dir=$(findup -f $exe); then
    cd "$dir"
    exec $exe "$@"
fi

exe=node_modules/.bin/cypress
if dir=$(findup -f $exe); then
    cd "$dir"
    exec $exe "$@"
fi

echo "You do not appear to be within a project with Cypress installed ($exe)" >&2
exit 1
