#!/usr/bin/env bash
set -euo pipefail

sudo='maybe-sudo-for-docker'

if [[ $# -eq 0 ]] && is-executable lazydocker; then
    exec $sudo lazydocker
fi

case ${1-} in
    b)
        shift
        exec $sudo docker build "$@"
        ;;
    c)
        shift
        exec $sudo docker container "$@"
        ;;
    i)
        shift
        exec $sudo docker image "$@"
        ;;
    r)
        shift
        exec $sudo docker run "$@"
        ;;
esac

exec $sudo docker "$@"
