#!/usr/bin/env bash
set -o errexit -o nounset -o pipefail

# Clean up stopped Docker containers and dangling (untagged) images
maybe-sudo-for-docker docker container prune
maybe-sudo-for-docker docker image prune
