#!/usr/bin/env bash
set -euo pipefail

# Resume the last stopped Docker image
# https://stackoverflow.com/a/37886136/167815
container=$(maybe-sudo-for-docker docker ps -qlf status=exited)

if [[ -n $container ]]; then
    exec maybe-sudo-for-docker docker start -ai "$container"
else
    echo "No stopped images found." >&2
    return 1
fi
