#!/usr/bin/env bash
set -o errexit -o nounset -o pipefail

args=
if [[ -f "$dir/public/includes/bootstrap.inc" ]]; then
    args="--root=$dir/public"
fi

exe1=bin/drush
if dir=$(findup -f $exe1); then
    exec "$dir/$exe1" $args "$@"
fi

exe2=vendor/bin/drush
if dir=$(findup -f $exe2); then
    exec "$dir/$exe2" $args "$@"
fi

exe3=public/vendor/bin/drush
if dir=$(findup -f $exe3); then
    exec "$dir/$exe3" $args "$@"
fi

echo "You do not appear to be within a project with Drush installed ($exe1, $exe2 or $exe3)" >&2
exit 1
