#!/usr/bin/env bash
set -o errexit -o nounset -o pipefail

# Docker Shell

# Set up SSH agent forwarding
if [[ -n $SSH_AUTH_SOCK ]]; then
    opt=(--volume $SSH_AUTH_SOCK:/tmp/ssh-agent --env SSH_AUTH_SOCK=/tmp/ssh-agent)
else
    opt=()
fi

# Build the command to run a shell on the specified image
image=${1:-ubuntu}
entrypoint=${2:-/bin/sh}
shift $(($# > 2 ? 2 : $#))

exec maybe-sudo-for-docker docker run --rm -it "${opt[@]}" "$@" --entrypoint "$entrypoint" "$image"
