#!/usr/bin/env bash
set -euo pipefail

# Stop most recent Docker container
container=${1:-}
if [[ -z $container ]]; then
    container=$(maybe-sudo-for-docker docker ps -qlf status=running)
fi

if [[ -n $container ]]; then
    exec maybe-sudo-for-docker docker stop $container
fi
