#!/usr/bin/env bash
set -o errexit -o nounset -o pipefail

# Stop all containers
containers=$(maybe-sudo-for-docker docker ps -qf status=running)

if [[ -n $containers ]]; then
    exec maybe-sudo-for-docker docker stop $containers
fi
