#!/usr/bin/env bash
set -o errexit -o nounset -o pipefail

# Stop most recent Docker container
container=${1:-}
if [[ -z $container ]]; then
    container=$(docker ps -qlf status=running)
fi

if [[ -n $container ]]; then
    exec docker stop $container
fi
