#!/usr/bin/env bash
set -euo pipefail

(
    hostname -f 2>/dev/null \
        || hostname 2>/dev/null \
        || cat /proc/sys/kernel/hostname
) \
    | tr '[:upper:]' '[:lower:]' \
    | sed 's/\.localdomain$//' \
    | sed 's/\.$//'
