#!/usr/bin/env bash
set -euo pipefail

# git pu = Push Upstream (push current branch and set as upstream)
remote=${1:-origin}
branch=${2:-HEAD}

# Set origin to the specified URL
if [[ $remote = *:* ]]; then
    git remote rm origin 2>/dev/null || true
    git remote add origin "$remote"
    remote='origin'
fi

exec git push -u "$remote" "$branch"
