#!/usr/bin/env bash
set -o errexit -o nounset -o pipefail

branch=$(git branch --show-current)

if [[ $branch != 'main' && $branch != 'master' ]]; then
    style lred 'The master branch is not checked out' >&2
    exit 1
fi

if [[ $branch != 'main' ]]; then
    style lblue 'Renaming to main...'
    git branch -m master main
    echo
fi

style lblue 'Fetching origin (if configured)...'
git fetch origin
echo
style lblue 'Setting upstream branch (if configured)...'
git branch -u origin/main
