#!/usr/bin/env bash
set -o errexit -o nounset -o pipefail

source "$HOME/.bash/ask"

if ask "Mark $PWD as safe in .gitconfig_local?"; then
    git config -f ~/.gitconfig_local --add safe.directory $PWD
fi
