#!/usr/bin/env bash
set -o errexit -o nounset -o pipefail

# ssh + tmux ('h' for 'ssH', because 's' is in use)
host=${1:-}
session=${2:-}

if [[ -z $host ]]; then
    echo "Usage: h <host> [session]" >&2
    exit 1
fi

# For 'h user@host ^', upload SSH public key - easier than retyping it
if [[ $# -eq 2 ]] && [[ "$session" = '^' ]]; then
    exec ssh-copy-id "$host"
fi

# For 'h user@host X', close the master connection
if [[ $# -eq 2 ]] && [[ "$session" = 'X' ]]; then
    exec ssh -O stop "$host"
fi

# If both tmux and dotfiles are installed on the remote server, run it remotely
result=0
ssh "$host" 'test -d ~/.dotfiles && command -v tmux &>/dev/null' || result=$?

if [[ $result -eq 255 ]]; then
    # SSH error, e.g. Could not resolve hostname
    exit $result
elif [[ $result -eq 0 ]]; then
    exec ssh "$host" -t "tmux -2 new -A -s \"${session:-\$USER}\""
fi

# Otherwise we'll run tmux locally...

# Use the short hostname as the session name
# (It may also include the username@ part if given)
if [[ -z $session ]]; then
    session=${host//\.*}
fi

# Try to avoid connecting to an existing session inside itself
if [[ -n ${TMUX:-} ]]; then
    current=$(tmux display-message -p '#S')

    if [[ $session = $current ]]; then
        echo "Already in '$session' session."
        exit 1
    fi
fi

# Allow nested sessions
export TMUX=

# Create a detached session (if there isn't one already)
tmux -2 new -s "$session" -d bash -l -c "ssh '$host'" 2>/dev/null || true

# Set the default command for new windows to connect to the same server
tmux set -t "$session" default-command "ssh '$host'"

# Connect to the session
exec tmux -2 attach -t "$session"
