#!/bin/bash
set -o nounset -o pipefail -o errexit

# ssh + tmux ('h' for 'ssH', because 's' is in use)
host="$1"
name="${2:-default}"

# For 'h user@host ^', upload SSH public key - easier than retyping it
if [[ $# -eq 2 ]] && [[ "$name" = '^' ]]; then
    exec ssh-copy-id "$host"
fi

# For 'h user@host X', close the master connection
if [[ $# -eq 2 ]] && [[ "$name" = 'X' ]]; then
    exec ssh -O stop "$host"
fi

# Not running tmux - run it over SSH
if [[ -z "${TMUX:-}" ]] && [[ "$TERM" != screen* ]]; then
    exec ssh -o ForwardAgent=yes -o StrictHostKeyChecking=accept-new "$host" \
        -t "command -v tmux &>/dev/null && tmux -2 new -A -s '$name' || bash -l"
fi

# Already running tmux *and* the user tried to specify a session name
if [[ $# -ge 2 ]]; then
    echo 'sessions should be nested with care, unset $TMUX to force' >&2
    exit 1
fi

# Already running tmux so connect without it
exec ssh -o ForwardAgent=yes -o StrictHostKeyChecking=accept-new "$host"
