#!/usr/bin/env bash
set -euo pipefail

count=$(ls -A1 | wc -l)

if [[ $count != 0 ]]; then
    echo "Current directory is not empty ($count files found)" >&2
    exit 1
fi

wgetx --strip https://wordpress.org/latest.tar.gz
