#!/usr/bin/env bash
set -euo pipefail

date=$(date +'%d %b %Y')
ipv4=$(curl -4s https://icanhazip.com || true)
ipv6=$(curl -6s https://icanhazip.com || true)

if [[ -z $ipv4 && -z $ipv6 ]]; then
    echo 'Unable to determine IPv4 or IPv6' >&2
    exit 1
fi

if [[ -z $ipv4 ]]; then
    ipv4="10.0.0.0 # $date (Dummy)"
else
    ipv4="$ipv4 # $date"
fi

if [[ -z $ipv6 ]]; then
    ipv6="fd00:: # $date (Dummy)"
else
    ipv6="$ipv6 # $date"
fi

exec ssh rainbow "
    sed -i \
        -e 's/^laptop .*/laptop $ipv4/' \
        -e 's/^laptop-ipv6 .*/laptop-ipv6 $ipv6/' \
        /etc/pve/firewall/cluster.fw
"
