#!/usr/bin/env bash
set -euo pipefail

if ! dir=$(findup -f artisan); then
    echo "You do not appear to be within a Laravel directory" >&2
    exit 1
fi

cd "$dir"

if ! ask 'This will drop and rebuild the database - are you sure?'; then
    exit 1
fi

artisan migrate:fresh --drop-views --seed
