#!/bin/bash
set -o nounset -o pipefail -o errexit

source $HOME/.bash/color.bash

if is-wsl; then
    multipass='multipass.exe'
else
    multipass='multipass'
fi

primary-name() {
    $multipass get client.primary-name | tr -d '\r'
}

case "${1:-}" in

    '') # Help
        color lcyan 'Multipass Shortcuts'
        echo "$(color lwhite 'mp l  [name]')  Launch a new instance with sensible defaults"
        echo "$(color lwhite 'mp h  [name]')  SSH to the given instance (or the first one listed)"
        echo "$(color lwhite 'mp d  [name]')  Suspend a running instance (down)"
        echo "$(color lwhite 'mp u  [name]')  Resume a stopped instance (up)"
        echo "$(color lwhite 'mp rm <name>')  Delete & purge instance (or --all)"
        echo
        echo "To list other commands run '$(color lwhite 'mp help')'."
        echo
        color lcyan 'Current instances'
        exec $multipass list
        ;;

    d|down) # Down
        shift
        $multipass suspend "$@"
        exec $multipass list
        ;;

    h) # SSH
        name="${2:-}"
        if [[ -z $name ]]; then
            name="$(primary-name)"
        fi

        ip=$($multipass list --format csv | awk -F , -v name="$name" 'NR > 1 && $1 == name { print $3 }')

        if [[ -n $ip ]] && [[ $ip != '--' ]] && [[ $ip != 'UNKNOWN' ]]; then
            # Remove the IP from the known hosts file because IPs are reused
            ssh-keygen -f ~/.ssh/known_hosts -R "$ip" 2>/dev/null

            # Connect via regular WSL SSH not Windows SSH, and launch tmux
            exec h "$ip"
        fi

        if [[ "$ip" = 'UNKNOWN' ]]; then
            echo >&2 "Cannot determine the IP of '$name'."
            echo >&2
            echo >&2 'Maybe disable and reenable the vEthernet adapter...'
            echo >&2 '    https://github.com/canonical/multipass/issues/706'
            echo >&2 'Or try creating a new instance and then restarting this one...'
            echo >&2 '    https://github.com/canonical/multipass/issues/1052'
            echo >&2
            echo >&2 'These are the running VMs:'
        else
            echo >&2 "Cannot determine the IP of '$name'. These are the running VMs:"
        fi

        echo >&2
        exec $multipass list >&2
        ;;

    l) # Launch
        primary=$(primary-name)
        name="${2:-$primary}"

        $multipass launch \
            --cloud-init ~/.multipass/cloud-config.yaml \
            --cpus 4 \
            --disk 5G \
            --mem 2G \
            --name "$name"

        if [[ $name = $primary ]]; then
            $multipass umount "$name:Home"
        fi

        exec mp h "$name"
        ;;

    rm) # Delete & purge
        shift
        exec $multipass delete --purge "$@"
        ;;

    scp) # Transfer
        shift
        exec $multipass transfer "$@"
        ;;

    u|up) # Up
        shift
        $multipass start "$@"
        exec $multipass list
        ;;

esac

exec $multipass "$@"
