#!/usr/bin/env bash
set -euo pipefail

list-instances() {
    instances=$(multipass list)
    style lwhite "$(echo "$instances" | head -n1)"
    echo "$instances" | tail -n+2
}

get-name() {
    if [[ $# -lt 1 ]]; then
        echo 'The name parameter is required' >&2
        exit 1
    fi

    name=$1
}

input() {
    local variable=$1
    local prompt=$2
    local default=$3

    read -p "$prompt [$default]: "
    eval "$variable=\${REPLY:-\$default}"
}

case "${1:-}" in

    '') # Help
        style lcyan,bold 'Multipass Shortcuts'
        echo "$(style lwhite 'mp l  [name]')  Launch a new instance with sensible defaults"
        echo "$(style lwhite 'mp h  [name]')  SSH to the given instance"
        echo "$(style lwhite 'mp d  [name]')  Suspend a running instance (down)"
        echo "$(style lwhite 'mp u  [name]')  Resume a stopped instance (up)"
        echo "$(style lwhite 'mp rm [name]')  Delete & purge instance (or --all)"
        echo
        echo "The default name is '$(style lwhite 'primary')'."
        echo
        echo "To list other commands run '$(style lwhite 'mp help')'."
        echo
        style lcyan,bold 'Current instances'
        list-instances
        ;;

    d|down) # Down
        shift
        multipass suspend "$@"
        list-instances
        ;;

    h|ssh) # SSH
        cmd=$1
        shift

        get-name "$@"
        shift

        $cmd "dave@$name.mshome.net" "$@"
        ;;

    l) # Launch
        shift

        get-name "$@"
        shift

        input cpus 'CPUs' 4
        input disk 'Disk' 20G
        input memory 'Memory' 4G
        input image 'Image' lts

        echo

        multipass launch \
            --cloud-init ~/.multipass/cloud-config.yaml \
            --name "$name" \
            --cpus "$cpus" \
            --disk "$disk" \
            --memory "$memory" \
            --network 'name=Hyper-V Internal Network,mode=manual' \
            "$@" \
            "$image"

        echo
        list-instances

        ssh-keygen -f ~/.ssh/known_hosts -R "$name.mshome.net" &>/dev/null
        ;;

    rm) # Delete & purge
        shift

        get-name "$@"
        shift

        multipass delete "$name" "$@"
        echo "Instance '$name' moved to the recycle bin."
        echo "Run 'mp purge' to permanently delete it."

        ssh-keygen -f ~/.ssh/known_hosts -R "$name.mshome.net" &>/dev/null
        ;;

    scp) # Transfer
        shift
        exec multipass transfer "$@"
        ;;

    u|up) # Up
        shift
        multipass start "$@"
        list-instances
        ;;

    *)
        exec multipass "$@"
        ;;

esac
