#!/usr/bin/env bash
set -o errexit -o nounset -o pipefail

if is-executable jq; then
    curl -fsS https://ipinfo.io/ | jq
else
    curl https://ipinfo.io/
    echo # Add missing trailing new line
fi
