#!/usr/bin/env bash
set -euo pipefail

if [[ -z ${1:-} ]]; then
    echo "Usage: $(basename "$0") <dbname>" >&2
    exit 1
fi

mysqldump --single-transaction --routines "$1" | bzip2 -9 > "$1.sql.bz2"
