#!/usr/bin/env bash
set -euo pipefail


if [[ $# -eq 0 ]]; then
    echo 'Usage: ntfy [topic] <message>'
    echo
    echo 'Export NTFY_TOPIC (in .bashrc_local) to set the default topic'
    exit
fi

if [[ $# -eq 1 ]]; then
    topic=${NTFY_TOPIC-}
    message=$1
else
    topic=$1
    message=$2
fi

if [[ -z $topic ]]; then
    echo 'ntfy: No topic set - export NTFY_TOPIC to set the default topic' >&2
    exit 1
fi

exec curl -d "$message" "https://ntfy.sh/$topic"
