#!/usr/bin/env bash
set -euo pipefail

exe=bin/phpunit
if dir=$(findup -f $exe); then
    cd "$dir"
    exec $exe "$@"
fi

exe=vendor/bin/phpunit
if dir=$(findup -f $exe); then
    cd "$dir"
    exec $exe "$@"
fi

echo "You do not appear to be within a project with PHPUnit installed ($exe)" >&2
exit 1
