#!/usr/bin/env bash
set -o errexit -o nounset -o pipefail

opts=()
if [[ -S $HOME/redis/redis.sock ]]; then
    opts+=(-s "$HOME/redis/redis.sock")
fi

if [[ ${1:-} =~ ^[0-9]+$ ]]; then
    # e.g. redis 1 keys '*'
    opts+=(-n)
fi

exec redis-cli "${opts[@]}" "$@"
