#!/bin/bash
set -o errexit -o nounset -o pipefail

source $HOME/.bash/color.bash

topic=${1:-}

if [[ -z $topic ]]; then
    echo "$(color lwhite Usage:) ref <topic> [edit|delete]"
    echo
    color lyellow 'Topics:'
    cd $HOME/.ref
    for file in *.txt; do
        echo "${file//.txt}"
    done
    exit
fi

if [[ ! $topic =~ ^[a-z0-9-]+$ ]]; then
    color lred "Invalid topic name '$topic'"
    exit 1
fi

if [[ ${2:-} = 'edit' ]]; then
    e "$HOME/.ref/$topic.txt"
elif [[ ! -f "$HOME/.ref/$topic.txt" ]]; then
    color lred 'Not Found'
elif [[ ${2:-} = 'delete' ]]; then
    rm -f "$HOME/.ref/$topic.txt"
    color lgreen 'Deleted'
else
    cat "$HOME/.ref/$topic.txt"
fi
