#!/usr/bin/env bash
set -o errexit -o nounset -o pipefail

topic=${1:-}

if [[ -z $topic ]]; then
    echo "$(style lwhite Usage:) ref <topic> [edit|delete]"
    echo
    style lyellow 'Topics:'
    cd $HOME/.ref
    for file in *.txt; do
        echo "${file//.txt}"
    done
    exit
fi

if [[ ! $topic =~ ^[a-z0-9-]+$ ]]; then
    style lred "Invalid topic name '$topic'"
    exit 1
fi

if [[ ${2:-} = 'edit' ]]; then
    e "$HOME/.ref/$topic.txt"
elif [[ ! -f "$HOME/.ref/$topic.txt" ]]; then
    style lred 'Not Found'
elif [[ ${2:-} = 'delete' ]]; then
    rm -f "$HOME/.ref/$topic.txt"
    style lgreen 'Deleted'
else
    bat-or-cat "$HOME/.ref/$topic.txt"
fi
