#!/bin/bash
set -o errexit -o nounset -o pipefail

source $HOME/.bash/color.bash

topic=${1:-}

if [[ -z $topic ]]; then
    echo "$(color lwhite Usage:) ref <topic> [edit]"
    exit
fi

if [[ ! $topic =~ ^[a-z0-9-]+$ ]]; then
    color lred "Invalid topic name '$topic'"
    exit 1
fi

if [[ ${2:-} = 'edit' ]]; then
    e "$HOME/.ref/$topic.txt"
elif [[ -f "$HOME/.ref/$topic.txt" ]]; then
    cat "$HOME/.ref/$topic.txt"
else
    color lred 'Not Found'
fi
