#!/usr/bin/env bash
set -euo pipefail

timezone=${1-}

if [[ -z $timezone ]]; then
    echo "Usage: $0 <timezone>"
    exit
fi

maybe-sudo timedatectl set-timezone "$timezone"

# This seemed to be necessary on Proxmox (Debian 11):
if [[ -f /etc/timezone ]]; then
    echo "$timezone" | sudo-write /etc/timezone
fi
