#!/bin/bash
set -o errexit -o nounset -o pipefail

# Upgrade tmux from 1.8 to 2.6
sudo yum remove -y tmux
sudo yum install -y https://dl.iuscommunity.org/pub/ius/archive/CentOS/7/x86_64/tmux2u-2.6-1.ius.centos7.x86_64.rpm
