#!/usr/bin/env bash
set -euo pipefail

sudo mkdir -p /local
sudo chgrp adm /local
sudo chmod g+ws /local

if ! is-root-user && ! is-in-group adm && ask "Add '$USER' to the 'adm' group?" Y; then
    sudo gpasswd -a "$USER" adm
fi
