#!/usr/bin/env bash
set -o errexit -o nounset -o pipefail

if [[ -f ~/.gitconfig_local ]]; then
    # shellcheck disable=SC2088
    echo '~/.gitconfig_local already exists' >&2
    exit 1
fi

if [[ $# -lt 1 ]]; then
    echo 'Usage: setup-identity <email> [name]' >&2
    exit 1
fi

email=$1
name=${2:-}

(
    echo "[user]"
    echo "    email = $email"
    if [[ -n $name ]]; then
        echo "    name = $name"
    fi
    echo ""
    vim='vim:' # Stop Vim actually parsing this when editing the script
    echo "# $vim ft=gitconfig"
) >~/.gitconfig_local
