#!/usr/bin/env bash
set -euo pipefail

# Parse arguments
exe=$(basename "$0")

help() {
    echo "Usage: $exe [options]"
    echo
    echo "Install PhpStorm and dependencies."
    echo
    echo "Options:"
    echo "  -h, --help      display this help"
    echo "  -r, --revert    uninstall everything"
}

args=$(getopt -n "$exe" -o 'hr' -l 'help,revert' -- "$@")
eval set -- "$args"

revert=false

while true; do
    case "$1" in
        -h | --help)    help; exit ;;
        -r | --revert)  revert=true; shift ;;
        --)             break; shift ;;
    esac
done

if $revert; then

    # Remove PhpStorm
    sudo snap remove phpstorm

    # Remove dependencies
    sudo apt purge -y \
        chromium-browser \
        default-jre \
        fonts-firacode \
        libgbm-dev \
        libgdm-dev \
        openjfx

else

    # Install dependencies
    # (Chromium installed to allow activation via browser)
    sudo apt install -y \
        chromium-browser \
        default-jre \
        fonts-firacode \
        libgbm-dev \
        libgdm-dev \
        openjfx

    # Install PhpStorm
    sudo snap install --classic phpstorm

fi
