#!/usr/bin/env bash
set -eno pipefail

# Parse arguments
exe=$(basename "$0")

help() {
    echo "Usage: $exe [options]"
    echo
    echo "Configure Sudo."
    echo
    echo "Options:"
    echo "  -h, --help      display this help"
    echo "  -r, --revert    remove the custom configuration"
}

args=$(getopt -n "$exe" -o 'hr' -l 'help,revert' -- "$@")
eval set -- "$args"

revert=false

while true; do
    case "$1" in
        -h | --help)    help; exit ;;
        -r | --revert)  revert=true; shift ;;
        --)             shift; break ;;
    esac
done

# Revert
if $revert; then
    sudo rm /etc/sudoers.d/dave
    exit
fi

# Apply
(
    # shellcheck disable=SC2016
    echo '# Always set $HOME so Vim writes temp files to /root/.vim/ instead of (e.g.) /home/dave/.vim/'
    echo 'Defaults always_set_home'
) | sudo-write /etc/sudoers.d/dave
