#!/usr/bin/env bash
set -o errexit -o nounset -o pipefail

source "$HOME/.bash/ask"

# Parse arguments
exe=$(basename "$0")

help() {
    echo "Usage: $exe [options]"
    echo
    echo "Install and configure MariaDB."
    echo
    echo "Options:"
    echo "  -h, --help      display this help"
    echo "  -r, --revert    uninstall everything"
}

args=$(getopt -n "$exe" -o 'hr' -l 'help,revert' -- "$@")
eval set -- "$args"

revert=false

while true; do
    case "$1" in
        -h | --help)    help; exit ;;
        -r | --revert)  revert=true; shift ;;
        --)             shift; break ;;
    esac
done

# Revert
if $revert; then
    sudo apt purge mariadb-client mariadb-server
    sudo snap remove dbeaver-ce
    exit
fi

# Install
sudo apt install -y mariadb-client mariadb-server

# Set password, etc. (interactive)
echo
if ask "Run mysql_secure_installation now?" Y; then
    sudo mysql_secure_installation
fi

# DBeaver (GUI)
echo
if ask "Install DBeaver?"; then
    sudo snap install dbeaver-ce
fi
