#!/usr/bin/env bash
set -euo pipefail

# Sudo
if is-executable sudo && [[ -d /etc/sudoers.d && ! -f /etc/sudoers.d/dave ]]; then
    if ask 'Configure sudo to always set $HOME (for Vim)?' Y; then
        setup-sudo
    fi
    echo
fi

# Locales
if ask 'Generate en_GB and en_US locales?' Y; then
    setup-locales
fi
echo

# Timezone
if ! is-wsl; then
    timezone='Europe/London'

    if ask "Set timezone to $timezone?" Y; then
        set-timezone "$timezone"
    fi

    echo
fi

# Hostname
if ! is-wsl; then
    default=Y
    if [[ $HOSTNAME = *.djm.me ]]; then
        default=N
    fi

    if ask 'Change the hostname?' $default; then
        read -p 'New hostname: ' hostname
        set-hostname "$hostname"
    fi

    echo
fi

# Swap
if ! is-wsl && [[ -z $(swapon -s) ]]; then
    if ask 'Create swap file?' Y; then
        read -p 'Size in GiB [2]: ' size_gb
        if [[ -z $size_gb ]]; then
            size_gb=2
        fi
        resize-swap "${size_gb}"
    fi

    echo
fi

# Upgrade
upgraded=false

if is-pve; then
    if [[ -f /etc/apt/sources.list.d/pve-enterprise.list ]] && ask 'Disable Proxmox Enterprise repo?' Y; then
        maybe-sudo rm /etc/apt/sources.list.d/pve-enterprise.list
    fi
    if [[ -f /etc/apt/sources.list.d/ceph.list ]] && grep -q enterprise.proxmox.com /etc/apt/sources.list.d/ceph.list && ask 'Disable Ceph repo?' Y; then
        maybe-sudo rm /etc/apt/sources.list.d/ceph.list
    fi
fi

if ask 'Install updates now?' Y; then
    maybe-sudo apt update
    maybe-sudo apt full-upgrade --auto-remove
    upgraded=true
fi

echo

# Firewall
if ! is-wsl && ! is-pve; then
    if ask 'Enable firewall (UFW)?' Y; then
        setup-firewall
    elif ask 'Enable Fail2ban?' Y; then
        setup-fail2ban
    fi
    echo
fi

# General utilities
for package in bat curl fzf httpie file pv tmux tree vim; do
    case $package in
        bat) command=batcat ;;
        httpie) command=http ;;
        *) command=$package ;;
    esac
    if ! is-executable "$command"; then
        if ask "Install $package?" Y; then
            maybe-sudo apt install -y "$package"
        fi
        echo
    fi
done

# Git utilities
if ! is-executable delta || ! is-executable lazygit; then
    if is-root-user; then
        echo 'Cannot install Homebrew as root - skipping Lazygit, Delta'
    elif ask 'Install Lazygit and Delta (via Homebrew)?'; then
        setup-git-utilities
    fi
    echo
fi

# Local directory
if ! is-wsl && [[ ! -d /local ]]; then
    if ask 'Create /local directory?' Y; then
        setup-local
    fi
    echo
fi

# WSL symlinks
if is-wsl; then
    if ask 'Create symlinks to Windows folders?'; then
        if path=$(wsl-mydocs-path 2>/dev/null); then
            ln -nsfv "$path" Documents
        fi
        if path=$(wsl-dropbox-path 2>/dev/null); then
            ln -nsfv "$path" Dropbox
        fi
    fi
    echo
fi

# Reboot
if ask 'Reboot now?'; then
    maybe-sudo reboot
fi
echo

# All done
echo 'Setup finished.'
