#!/bin/bash
set -o errexit -o pipefail -o nounset

source ~/.bash/color.bash

color lblue 'Downloading APT package information'
sudo apt update

color lblue 'Upgrading installed packages'
sudo apt full-upgrade -y

color lblue 'Installing additional packages'
# Note: vim-gnome adds X11 clipboard support
sudo apt install -y dos2unix php-cli rename tree unzip vim-gnome whois zip

color lblue 'Removing unneeded packages'
sudo apt autoremove -y

color lblue 'Setting the default editor to Vim'
sudo update-alternatives --set editor /usr/bin/vim.basic
