#!/usr/bin/env bash
set -euo pipefail

if [[ $# -lt 1 ]]; then
    echo 'Usage: setup-identity <email> [name]' >&2
    exit 1
fi

email=$1
name=${2:-}

if [[ -n $name ]]; then
    git config -f .gitconfig_local user.name "$name"
fi

git config -f .gitconfig_local user.email "$email"
