#!/usr/bin/env bash
set -o errexit -o nounset -o pipefail

source "$HOME/.bash/color"

# Parse arguments
exe=$(basename "$0")

help() {
    echo "Usage: $exe [options]"
    echo
    echo "Install Git-related tools (Lazy Git, Delta)."
    echo
    echo "Options:"
    echo "  -h, --help      display this help"
    echo "  -r, --revert    uninstall everything"
}

args=$(getopt -n "$exe" -o 'hr' -l 'help,revert' -- "$@")
eval set -- "$args"

revert=false

while true; do
    case "$1" in
        -h | --help)    help; exit ;;
        -r | --revert)  revert=true; shift ;;
        --)             shift; break ;;
    esac
done

# Lazy Git - https://github.com/jesseduffield/lazygit
if ! is-executable brew; then
    color lred "Skipped Lazy Git because it requires Homebrew (run 'setup-brew' to install it)"
elif $revert; then
    color lcyan 'Uninstalling Lazy Git...'
    brew uninstall jesseduffield/lazygit/lazygit || true
else
    color lcyan 'Installing Lazy Git...'
    brew install jesseduffield/lazygit/lazygit
fi

echo

# Delta - https://github.com/dandavison/delta
if ! is-executable brew; then
    color lred "Skipped Delta because it requires Homebrew (run 'setup-brew' to install it)"
elif $revert; then
    color lcyan 'Uninstalling Delta...'
    brew uninstall git-delta || true
else
    color lcyan 'Installing Delta...'
    brew install git-delta
fi

echo

# Done
color lcyan 'Done.'
