#!/usr/bin/env bash
set -o errexit -o nounset -o pipefail
shopt -s nullglob

# Parse arguments
exe=$(basename "$0")

help() {
    echo "Usage: $exe [options]"
    echo
    echo "Install/upgrade PsySH (PHP REPL)."
    echo
    echo "Options:"
    echo "  -h, --help      display this help"
    echo "  -r, --revert    uninstall PsySH"
}

args=$(getopt -n "$exe" -o 'hr' -l 'help,revert' -- "$@")
eval set -- "$args"

revert=false

while true; do
    case "$1" in
        -h | --help)    help; exit ;;
        -r | --revert)  revert=true; shift ;;
        --)             shift; break ;;
    esac
done

# Install/uninstall PsySH
if $revert; then
    rm -fv ~/.bin/local/psysh
else
    curl https://psysh.org/psysh > ~/.bin/local/psysh
    chmod +x ~/.bin/local/psysh
fi
