#!/usr/bin/env bash
set -euo pipefail

added_to_group=false
exe=$(basename "$0")
revert=false

main() {
    parse-arguments "$@"

    if $revert; then
        uninstall-docker
        remove-user-from-docker-group
        uninstall-lazy-docker
        uninstall-dive
    else
        enable-universe-repository # Not reverted
        install-docker
        add-user-to-docker-group
        install-lazy-docker
        install-dive
    fi

    finished
}

help() {
    echo "Usage: $exe [options]"
    echo
    echo "Install Docker, Lazy Docker and Dive."
    echo
    echo "Options:"
    echo "  -h, --help      display this help"
    echo "  -r, --revert    uninstall everything"
}

parse-arguments() {
    local args
    args=$(getopt -n "$exe" -o 'hr' -l 'help,insecure-group,revert' -- "$@")
    eval set -- "$args"

    while true; do
        case "$1" in
            -h | --help)    help; exit ;;
            -r | --revert)  revert=true; shift ;;
            --)             shift; break ;;
        esac
    done
}

enable-universe-repository() {
    # Make sure the 'universe' repository is enabled
    # TODO: If I need this for any other scripts, move it into its own script
    if ! grep -q '^deb .* universe' /etc/apt/sources.list; then
        style lcyan,bold "Enabling 'universe' repository..."
        maybe-sudo add-apt-repository --yes universe
        echo
    fi
}

install-docker() {
    style lcyan,bold 'Installing Docker...'
    maybe-sudo apt install -y docker.io docker-compose docker-compose-v2 docker-buildx
    echo
}

uninstall-docker() {
    style lcyan,bold 'Uninstalling Docker...'
    maybe-sudo apt purge --auto-remove docker.io docker-compose docker-compose-v2 docker-buildx
    echo
}

add-user-to-docker-group() {
    if ! is-root-user && ! is-in-group docker; then
        # Security info: https://docs.docker.com/engine/install/linux-postinstall/
        style lcyan,bold "Configuring group membership..."
        if ask "Add '$USER' to the 'docker' group? (WARNING: This is less secure!)" N; then
            sudo gpasswd -a "$USER" docker
            added_to_group=true
        fi
        echo
    fi
}

remove-user-from-docker-group() {
    style lcyan,bold "Deleting the 'docker' group..."
    maybe-sudo groupdel docker || true
    echo
}

check-for-homebrew() {
    if ! is-executable brew; then
        style lred "Homebrew is not installed (run 'setup-brew' to install it)"
        return 1
    fi
}

install-lazy-docker() {
    style lcyan,bold 'Installing Lazy Docker...'
    if check-for-homebrew; then
        # https://github.com/jesseduffield/lazydocker
        brew install jesseduffield/lazydocker/lazydocker
    fi
    echo
}

uninstall-lazy-docker() {
    style lcyan,bold 'Uninstalling Lazy Docker...'
    if check-for-homebrew; then
        brew uninstall jesseduffield/lazydocker/lazydocker || true
    fi
    echo
}

install-dive() {
    style lcyan,bold 'Installing Dive...'
    if check-for-homebrew; then
        brew install dive
    fi
    echo
}

uninstall-dive() {
    style lcyan,bold 'Uninstalling Dive...'
    if check-for-homebrew; then
        brew uninstall dive || true
    fi
    echo
}

finished() {
    style lcyan,bold 'Done.'

    if $added_to_group && ! is-in-group docker; then
        echo
        echo 'You may need to log out and back in to refresh your groups, or run:'
        # shellcheck disable=SC2016
        echo '  exec sudo su -l "$USER"'
    fi
}

main "$@"
