#!/usr/bin/env bash
set -euo pipefail

# Parse arguments
exe=$(basename "$0")

help() {
    echo "Usage: $exe [options]"
    echo
    echo "Install Homebrew."
    echo
    echo "Options:"
    echo "      --auto      skip if already installed"
    echo "  -h, --help      display this help"
    echo "  -r, --revert    uninstall"
}

args=$(getopt -n "$exe" -o 'hr' -l 'help,revert' -- "$@")
eval set -- "$args"

auto=false
revert=false

while true; do
    case "$1" in
        --auto) auto=true; shift ;;
        -h | --help)    help; exit ;;
        -r | --revert)  revert=true; shift ;;
        --)             shift; break ;;
    esac
done

if $revert; then
    if $auto && [[ ! -f /home/linuxbrew/.linuxbrew/bin/brew ]]; then
        exit
    fi
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)"
else
    if $auto && [[ -f /home/linuxbrew/.linuxbrew/bin/brew ]]; then
        exit
    fi
    # https://docs.brew.sh/Installation
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

if ! $auto; then
    echo
    echo "Run 'reload' to update \$PATH."
fi
