#!/usr/bin/env bash
set -o errexit -o nounset -o pipefail

# Parse arguments
exe=$(basename "$0")

help() {
    echo "Usage: $exe [options]"
    echo
    echo "Install and configure Apache."
    echo
    echo "Options:"
    echo "  -h, --help      display this help"
    echo "  -r, --revert    uninstall everything"
}

args=$(getopt -n "$exe" -o 'hr' -l 'help,revert' -- "$@")
eval set -- "$args"

revert=false

while true; do
    case "$1" in
        -h | --help)    help; exit ;;
        -r | --revert)  revert=true; shift ;;
        --)             shift; break ;;
    esac
done

# Revert
if $revert; then
    sudo apt purge --auto-remove apache2 apache2-utils
    sudo rm -f /etc/apache2/conf-enabled/z_dave-common.conf
    sudo gpasswd -d "$USER" www-data
    exit
fi

# Install
color lcyan 'Installing Apache...'
sudo apt install -y apache2 apache2-utils
echo

# Enable modules
color lcyan 'Enabling modules...'
sudo a2enmod \
    headers \
    http2 \
    proxy_fcgi \
    rewrite \
    ssl
echo

# Global configuration
color lcyan 'Updating Apache configuration...'

sudo-write /etc/apache2/conf-enabled/z_dave-common.conf <~/.templates/apache/common.conf

if [[ ! -f /etc/apache2/conf-enabled/z_dave-ssl.conf ]]; then
    # This will be overwritten by 'setup-certbot'
    sudo-write /etc/apache2/conf-enabled/z_dave-ssl.conf <~/.templates/apache/ssl-snakeoil.conf
fi

if [[ -f /etc/apache2/sites-enabled/000-default.conf && -f /etc/apache2/sites-available/default-ssl.conf ]]; then
    # Enable the default SSL site, but use the SSL certificate defined above
    sudo sed -Ei 's/^(\s+)(SSLCertificate)/\1#\2/' /etc/apache2/sites-available/default-ssl.conf
    sudo a2ensite default-ssl
fi

echo

# Set permissions
color lcyan 'Setting permissions on /var/www/ and /etc/apache2/sites-enabled/...'
# Note: I put config files directly into sites-enabled, not sites-available, because it's so
# rare that I want to be able to disable a site, so the extra step isn't really necessary
sudo chgrp -R www-data /var/www/ /etc/apache2/sites-enabled/
sudo chmod -R ug+rwX,o-rwx /var/www/
sudo chmod -R ug+rwX /etc/apache2/sites-enabled/
sudo find /var/www/ /etc/apache2/sites-enabled/ -type d -exec chmod g+s '{}' +
echo

# Restart Apache
color lcyan 'Restarting Apache...'
sudo systemctl restart apache2
sudo systemctl status apache2
echo

# Apache group
added_to_group=false

if ! is-root-user && ! is-in-group www-data; then
    color lcyan "Configuring group membership..."
    if ask "Add '$USER' to the 'www-data' group? (WARNING: This is less secure!)" N; then
        sudo gpasswd -a "$USER" www-data
        added_to_group=true
    fi
    echo
fi

# Done
color lcyan 'Done.'

if $added_to_group && ! is-in-group www-data; then
    echo
    echo 'You may need to log out and back in to refresh your groups, or run:'
    # shellcheck disable=SC2016
    echo '  exec sudo su -l "$USER"'
fi
