#!/usr/bin/env bash
set -euo pipefail

if [[ ! -d /etc/apache2/sites-enabled ]]; then
    echo 'Apache is not installed' >&2
    exit 1
fi

if [[ ! -d /local ]]; then
    setup-local
fi

mkdir -p /local/temp/public

cp $HOME/.templates/temp/.htaccess /local/temp/public/
cp $HOME/.templates/temp/phpinfo.php /local/temp/public/

hostname=$(hostname -f)

sudo tee /etc/apache2/sites-available/temp.conf >/dev/null <<END
<VirtualHost *:443>
    ServerName temp.$hostname
    DocumentRoot /local/temp/public
</VirtualHost>

<Directory /local/temp/public>
    AllowOverride All
    Require all granted
</Directory>
END

sudo a2ensite temp
sudo systemctl reload apache2
sudo systemctl status apache2
