#!/usr/bin/env bash
set -euo pipefail

# Parse arguments
exe=$(basename "$0")

help() {
    echo "Usage: $exe [options]"
    echo
    echo "Install and configure Apache."
    echo
    echo "Options:"
    echo "  -h, --help      display this help"
    echo "  -r, --revert    uninstall everything"
}

args=$(getopt -n "$exe" -o 'hr' -l 'help,revert' -- "$@")
eval set -- "$args"

revert=false

while true; do
    case "$1" in
        -h | --help)    help; exit ;;
        -r | --revert)  revert=true; shift ;;
        --)             shift; break ;;
    esac
done

# Revert
if $revert; then
    sudo apt purge --auto-remove apache2 apache2-utils elinks ssl-cert
    sudo rm -f /etc/apache2/conf-enabled/z_dave-common.conf
    sudo gpasswd -d "$USER" www-data
    exit
fi

# Install
style lcyan,bold 'Installing Apache...'
sudo apt install -y apache2 apache2-utils elinks ssl-cert
echo

# Enable modules
style lcyan,bold 'Enabling modules...'

sudo a2dismod mpm_prefork

sudo a2enmod \
    headers \
    http2 \
    mpm_event \
    rewrite \
    ssl
echo

# Global configuration
style lcyan,bold 'Updating Apache configuration...'

sudo a2disconf other-vhosts-access-log
sudo-write /etc/apache2/conf-enabled/z_dave-common.conf <~/.templates/apache/common.conf

if [[ ! -f /etc/apache2/conf-enabled/z_dave-ssl.conf ]]; then
    # This will be overwritten by 'setup-certbot'
    sudo-write /etc/apache2/conf-enabled/z_dave-ssl.conf <~/.templates/apache/ssl-snakeoil.conf
fi

if [[ -f /etc/apache2/sites-enabled/000-default.conf ]]; then
    sudo a2dissite 000-default
fi

if [[ ! -f /etc/apache2/sites-available/001-default.conf ]]; then
    sudo-write /etc/apache2/sites-available/001-default.conf <~/.templates/apache/default-site.conf
    sudo a2ensite 001-default
fi

echo

# Set permissions
style lcyan,bold 'Setting permissions on /var/www/ and /etc/apache2/sites-available/...'
sudo chgrp -R www-data /var/www/ /etc/apache2/sites-available/
sudo chmod -R ug+rwX,o-rwx /var/www/
sudo chmod -R ug+rwX /etc/apache2/sites-available/
sudo find /var/www/ /etc/apache2/sites-available/ -type d -exec chmod g+s '{}' +
echo

# Restart Apache
style lcyan,bold 'Restarting Apache...'
sudo systemctl restart apache2
sudo systemctl status apache2
echo

# Apache group
added_to_group=false

if ! is-root-user && ! is-in-group www-data; then
    style lcyan,bold "Configuring group membership..."
    if ask "Add '$USER' to the 'www-data' group? (WARNING: This is less secure!)" N; then
        sudo gpasswd -a "$USER" www-data
        added_to_group=true
    fi
    echo
fi

# Done
style lcyan,bold 'Done.'

if $added_to_group && ! is-in-group www-data; then
    echo
    echo 'You may need to log out and back in to refresh your groups, or run:'
    # shellcheck disable=SC2016
    echo '  exec sudo su -l "$USER"'
fi
