#!/usr/bin/env bash
set -o errexit -o nounset -o pipefail

# Parse arguments
exe=$(basename "$0")

help() {
    echo "Usage: $exe [options]"
    echo
    echo "Install various CLI utilities (bat, fzf, httpie, vim, etc.)."
    echo
    echo "Options:"
    echo "  -h, --help      display this help"
    echo "  -r, --revert    uninstall everything"
}

args=$(getopt -n "$exe" -o 'hr' -l 'help,revert' -- "$@")
eval set -- "$args"

revert=false

while true; do
    case "$1" in
        -h | --help)    help; exit ;;
        -r | --revert)  revert=true; shift ;;
        --)             break; shift ;;
    esac
done

# Note: vim-gtk adds X11 clipboard support - but it takes much longer to install :(
packages='
    bat
    curl
    fzf
    httpie
    pv
    tree
    tmux
    vim-gtk
'

if $revert; then
    sudo apt purge --auto-remove $packages
else
    sudo apt install -y $packages
fi
