#!/usr/bin/env bash
set -euo pipefail

if [[ $# -ne 1 ]]; then
    echo "Usage: $(basename "$0") NAME"
    echo
    echo 'NAME should be a repository from https://github.com/d13r?tab=repositories'
    echo 'It will be cloned into the current directory'
    exit
fi

name=$1

if [[ ! -e $name ]]; then
    git clone "git@github.com:d13r/$name.git"
    echo
fi

cd "$name"

if [[ ! -f bin/setup ]]; then
    echo "There is no bin/setup script in $name/" >&2
    exit 1
fi

exec bin/setup
