#!/usr/bin/env bash
set -euo pipefail

# In case something goes wrong, uncomment this temporarily to disable this
# functionality everywhere it is used
#exec ssh "$@"

# Read from .bashrc_remote
# Remove commands and blank lines
bashrc=$(egrep -v '(^$|^#)' $HOME/.bashrc_remote )

# Replace ' with '\'' (that is close quote, escaped single quote, open quote - because Bash doesn't allow \' inside a string)
bashrc=${bashrc//\'/\'\\\'\'}

# Pass that to Bash on the remote server
exec ssh "$@" -t "bash --rcfile <(echo '$bashrc')"
