#!/usr/bin/env bash
set -euo pipefail

# If no command was given, using 'env' will cause it to print all environment variables
if [[ $# -eq 0 ]]; then
    exec sudo
fi

# If the first argument is an option rather than a command, we can't do this
if [[ $1 = -* ]]; then
    exec sudo "$@"
fi

# This makes it possible to use 'sudo' with programs in ~/.bin/, installed via
# Homebrew, or otherwise not in the default path used by sudo
# https://stackoverflow.com/a/29400598/167815
exec sudo -E env "PATH=$PATH" "$@"
