#!/bin/bash
set -o nounset -o pipefail -o errexit
shopt -s nullglob

TITLE="\e[97;1;4m" # White, bold, underline
RESET="\e[0m"

exe="$(basename "$0")"

# Locate the bin/ directory
if ! root="$(findup -d bin)" || [[ $root = '/' ]]; then
    echo "'bin' directory not found" >&2
    exit 1
fi

# Subdirectory?
bin="$root/bin"
prefix=''

while [[ $# -gt 0 ]] && [[ -d "$bin/${1:-}" ]]; do
    bin="$bin/$1"
    prefix="$prefix$1 "
    shift
done

# Run executable?
if [[ $# -gt 0 ]]; then
    cmd="$1"

    for executable in "$bin/$cmd"{,.*}; do
        if [[ -f "$executable" ]]; then
            shift
            exec "$executable" "$@"
        fi
    done

    echo "Executable '$prefix$cmd' not found" >&2
    exit 1
fi

# Display list of executables
list_executables() {
    local cmd="$1"
    local dir="$2"

    for file in "$dir/"*; do
        [[ -e $file ]] || continue

        name="$(basename "$file")" # Remove path
        name="${name%%.*}"         # Remove extension

        if [[ ${name:0:1} = '_' ]]; then
            : # Skip includes (files starting with "_")
        elif [[ -d $file ]]; then
            list_executables "$cmd$name " "$file"
        elif [[ ! -x $file ]]; then
            : # Skip non-executable files
        elif [[ "$name" == *" "* ]]; then
            # Spaces in the name
            echo "$cmd'$name'"
        else
            echo "$cmd$name"
        fi
    done
}

(
    if [[ -n $prefix ]]; then
        echo -e "${TITLE}Matching Executables${RESET}"
    else
        echo -e "${TITLE}Available Executables${RESET}"
    fi

    list_executables "$exe $prefix" "$bin"
) | less
