#!/bin/bash
set -o nounset -o pipefail -o errexit
shopt -s nullglob

#================================================================================
# Script runner - (c) Dave James Miller 2015-2023 - MIT License
#================================================================================

WHITE_UNDERLINE="\e[37;1;4m"
RESET="\e[0m"

exe="$(basename "$0")"

# Locate the scripts directory
if ! root="$(findup -d scripts)"; then
    echo "'scripts' directory not found" >&2
    exit 1
fi

# Subdirectory?
scripts="$root/scripts"
prefix=''

while [[ $# -gt 0 ]] && [[ -d "$scripts/${1:-}" ]]; do
    scripts="$scripts/$1"
    prefix="$prefix$1 "
    shift
done

# Run script?
if [[ $# -gt 0 ]]; then
    cmd="$1"

    for script in "$scripts/$cmd"{,.*}; do
        if [[ -f "$script" ]]; then
            shift
            exec "$script" "$@"
        fi
    done

    echo "Script '$prefix$cmd' not found" >&2
    exit 1
fi

# Display list of scripts
list_scripts() {
    local cmd="$1"
    local dir="$2"

    for file in "$dir/"*; do
        [[ -e $file ]] || continue

        name="$(basename "$file")" # Remove path
        name="${name%%.*}"         # Remove extension

        if [[ ${name:0:1} = '_' ]]; then
            : # Skip includes (files starting with "_")
        elif [[ -d $file ]]; then
            list_scripts "$cmd$name " "$file"
        elif [[ "$name" == *" "* ]]; then
            # Spaces in the name
            echo "$cmd'$name'"
        else
            echo "$cmd$name"
        fi
    done
}

(
    if [[ -n $prefix ]]; then
        echo -e "${WHITE_UNDERLINE}Matching Scripts${RESET}"
    else
        echo -e "${WHITE_UNDERLINE}Available Scripts${RESET}"
    fi

    list_scripts "$exe $prefix" "$scripts"
) | less
