#!/usr/bin/env bash
set -o errexit -o nounset -o pipefail

if [[ -z ${1:-} ]]; then
    echo "Usage: tarx <filename>"
elif [[ -f $1 ]]; then
    case $1 in
        *.tar.bz2)  tar xjf "$1"    ;;
        *.tar.gz)   tar xzf "$1"    ;;
        *.7z)       7z x "$1"       ;;
        *.bz2)      bunzip2 "$1"    ;;
        *.gz)       gunzip "$1"     ;;
        *.rar)      unrar e "$1"    ;;
        *.tar)      tar xf "$1"     ;;
        *.tbz2)     tar xjf "$1"    ;;
        *.tgz)      tar xzf "$1"    ;;
        *.zip)      unzip "$1"      ;;
        *.Z)        uncompress "$1" ;;
        *)          echo "'$1' cannot be extracted by tarx" >&2 ;;
    esac
else
    echo "'$1' is not a valid file" >&2
fi
