#!/usr/bin/env bash
set -euo pipefail

# Start SSH agent
# Prompt for SSH key passphrase
# If successful, start (or reconnect to) Tmux
# The SSH agent exits automatically when Tmux exits
exec ssh-agent mate-terminal --maximize -e 'bash -lc "ssh-add ~/.ssh/mi-dave.key && exec tmux -2 new -A -s x2go x2go-menu"'
