#!/usr/bin/env bash
set -euo pipefail

case "${1:-}" in

    a) # Apply
        shift
        exec terraform apply "$@"
        ;;

    an) # Apply No Refresh
        shift
        exec terraform apply -refresh=false "$@"
        ;;

    ar) # Apply Refresh Only
        shift
        exec terraform apply -refresh-only "$@"
        ;;

    i) # Init
        shift
        exec terraform init "$@"
        ;;

    mv) # State Move
        shift
        exec terraform state mv "$@"
        ;;

    o) # Output
        shift
        exec terraform output "$@"
        ;;

    p) # Plan
        shift
        exec terraform plan "$@"
        ;;

    v) # Validate
        shift
        exec terraform validate "$@"
        ;;

    *)
        exec terraform "$@"
        ;;

esac

