#!/usr/bin/env bash
set -o errexit -o nounset -o pipefail

session=${1:-$USER}

# Launch tmux
if [[ -z ${TMUX:-} ]]; then
    exec tmux -2 new -A -s "$session"
fi

# Already running - switch session
current=$(tmux display-message -p '#S')

if [[ $session = $current ]]; then
    echo "Already in '$session' session."
    exit 1
fi

tmux -2 new -d -s "$session" 2>/dev/null
tmux -2 switch -t "$session"
