#!/bin/sh

session="${1:-default}"

# Launch tmux
if [ -z "$TMUX" ]; then
    exec tmux -2 new -A -s "$session"
fi

# Already running - switch session
tmux -2 new -d -s "$session" 2>/dev/null &&
tmux -2 switch -t "$session"
