#!/usr/bin/env bash
set -euo pipefail

if [[ -d "$HOME/Desktop" ]]; then
    file="$HOME/Desktop/TODO.txt"
else
    file="$HOME/TODO.txt"
fi

help() {
    echo "Usage: todo [edit]"
    echo "       todo add <task>"
    echo "       todo list"
    echo "       todo delete"
}

case "${1:-edit}" in
    add|a|+)
        shift
        [[ -f $file ]] && echo >> "$file"
        if [[ $# -gt 0 ]]; then
            echo "$@" >> "$file"
        else
            cat >> "$file"
        fi
        ;;
    delete|del|rm)
        echo "Current TODO list:"
        echo "------------------"
        cat "$file"
        echo "------------------"
        echo
        rm -i "$file"
        ;;
    edit|e)
        exec vim "$file"
        ;;
    help|--help|-h)
        help
        ;;
    list|ls|l|view|v|cat|c)
        cat "$file"
        ;;
    *)
        help >&2
        exit 1
        ;;
esac
