#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/.."

RESET=$'\e[0m'
LCYAN=$'\e[96m'

echo "${LCYAN}Downloading bin${RESET}"
wget https://github.com/bin-cli/bin-cli/releases/latest/download/bin -O ~/.bin/bin
chmod +x ~/.bin/bin

echo "${LCYAN}Downloading bin.1.gz${RESET}"
wget https://github.com/bin-cli/bin-cli/releases/latest/download/bin.1.gz -O ~/.local/share/man/man1/bin.1.gz

echo "${LCYAN}Downloading binconfig.5.gz${RESET}"
wget https://github.com/bin-cli/bin-cli/releases/latest/download/binconfig.5.gz -O ~/.local/share/man/man5/binconfig.5.gz
