#!/usr/bin/env bash
set -euo pipefail

exec powershell.exe -Command "
    Start-Process powershell.exe -Verb RunAs -ArgumentList \"
        Set-NetIPInterface -ifAlias 'vEthernet (Default Switch)' -Forwarding Enabled
        Set-NetIPInterface -ifAlias 'vEthernet (WSL)' -Forwarding Enabled
        Get-NetIPInterface | Select-Object InterfaceAlias,AddressFamily,Forwarding | Sort-Object InterfaceAlias,AddressFamily | Out-String
        Pause
    \"
"
