#!/usr/bin/env bash
set -euo pipefail

exe="$(wsl-localappdata-path)/Programs/PhpStorm/bin/phpstorm64.exe"

if [[ ! -f $exe ]]; then
    echo "phpstorm64.exe not found" >&2
    exit 1
fi

exec "$exe" "$@"
