#!/usr/bin/env bash
set -euo pipefail

# Source: https://github.com/microsoft/WSL/issues/4288#issuecomment-778790363
exec powershell.exe -Command "
    Start-Process powershell.exe -Verb RunAs -ArgumentList \"
        Set-NetIPInterface -ifAlias 'vEthernet *' -Forwarding Enabled
        Get-NetIPInterface | Select-Object InterfaceAlias,AddressFamily,Forwarding | Sort-Object InterfaceAlias,AddressFamily | Out-String
        Pause
    \"
"
