#!/bin/bash

#================================================================================
# USAGE:
# wget djm.me/cfg
# . cfg
#================================================================================

# Run this in a sub-process, so there's no variables left over at the end
(

    # Should be in home directory anyway, but just in case...
    cd

    # WSL defaults to umask 000
    umask 022

    # Make sure this file is in the home directory
    if [ ! -f cfg ]; then
        echo 'Script must be named ~/cfg' >&2
        exit 1
    fi

    # Check git is available
    if ! command -v git >/dev/null; then
        if ! (sudo apt-get update && sudo apt-get install git); then
            echo 'Git is not installed' >&2
            exit 2
        fi
    fi

    # Check .git doesn't exist
    if [ -d .git ]; then
        echo '~/.git exists' >&2
        exit 3
    fi

    # Helper function
    ask() {
        local prompt default reply

        while true; do

            if [ "${2:-}" = "Y" ]; then
                prompt="Y/n"
                default=Y
            elif [ "${2:-}" = "N" ]; then
                prompt="y/N"
                default=N
            else
                prompt="y/n"
                default=
            fi

            # Ask the question (not using "read -p" as it uses stderr not stdout)
            echo -n "$1 [$prompt] "

            # Read the answer (use /dev/tty in case stdin is redirected from somewhere else)
            read reply </dev/tty

            # Default?
            if [ -z "$reply" ]; then
                reply=$default
            fi

            # Check if the reply is valid
            case "$reply" in
                Y*|y*) return 0 ;;
                N*|n*) return 1 ;;
            esac

        done
    }

    # Alberon dotfiles have been split from mine (18 Mar 2018)
    echo "This script (djm.me/cfg) is for Dave's dotfiles only."
    echo "If you are not Dave, please press N then run:"
    echo
    echo '    rm -f cfg'
    echo '    wget alberon.uk/cfg'
    echo '    . cfg'
    echo
    ask 'Continue?' Y || exit 4

    # Download the repository
    echo 'Initialising Git repository...'
    echo
    git init || exit 5
    git remote add origin "https://github.com/davejamesmiller/dotfiles.git" || exit 6
    git remote set-url --push origin "git@github.com:davejamesmiller/dotfiles.git" || exit 7
    echo
    echo 'Fetching Git repository...'
    echo
    git fetch origin || exit 8

    # Update the working directory
    # Delete or move any conflicting files (usually .bashrc and .bash_logout)
    echo
    echo 'Updating working directory...'
    echo
    i=0
    while true; do

        # Try to update
        result="$(git checkout origin/master -b master 2>&1)"

        # If it succeeds, we're done
        if [ $? -eq 0 ]; then
            if [ $i -gt 0 ]; then
                echo
            fi
            echo "$result"
            break
        fi

        # If it fails, move or delete the conflicting file
        # Old versions of git have this message:
        file="$(echo "$result" | sed -n "/error: Untracked working tree file/ { s/error: Untracked working tree file '\\(.*\\)' would be overwritten by merge./\\1/; p; q }")"
        if [ -z "$file" ]; then
            # Newer versions of git have a different message, split across two lines:
            file="$(echo "$result" | sed -n "/error: The following untracked working tree files would be overwritten by checkout:/ { n; s/\\s\\+\\(.*\\)/\\1/; p; q }")"
        fi
        if [ -n "$file" ] && [ "$file" != "$result" ]; then

            read -p "Backup $file? [y/N] " answer
            case $answer in
                y*|Y*)
                    dest="$file.orig"
                    rm -f "$dest"
                    mv "$file" "$dest"
                    echo "  Moved to $dest"
                    ;;
                *)
                    rm -f "$file"
                    ;;
            esac

        else

            # Unknown error
            echo "Unknown error in 'git checkout':" >&2
            echo "$result" >&2
            exit 9

        fi

        # Prevent infinite loop - just in case
        ((i++))
        if [ $i -ge 100 ]; then
            echo
            echo 'Detected possible infinite loop - giving up' >&2
            exit 10
        fi

    done

    echo

    # Remove this script
    # (Note: $0 is not set because we 'source' this file)
    if [ -f cfg ]; then
        rm -f cfg
    fi

)

ret=$?
if [ $ret == 0 ]; then

    # Run any post-install commands, e.g. prepare config file
    [ -x ~/bin/cfg-install ] && ~/bin/cfg-install

    # Run post-update script
    [ -x ~/bin/cfg-update ] && ~/bin/cfg-update

    # Load the new bash config
    exec bash -l

else

    echo
    echo "SETUP FAILED with error code $ret" >&2

fi
