#!/bin/bash

#================================================================================
# USAGE:
# wget djm.me/cfg
# . cfg
#================================================================================

# Run this in a sub-process
(
    set -o errexit -o pipefail -o nounset

    # Should be in home directory anyway, but just in case...
    cd

    # WSL defaults to umask 000
    umask 022

    # Helpers
    say() {
        echo -en "\e[94m" # Light blue
        echo -n "$1"
        echo -e "\e[0m"
    }

    fail() {
        echo >&2 -en "\e[91m" # Light red
        echo >&2 -n "$1"
        echo >&2 -e "\e[0m"
        exit 1
    }

    # Sanity checks
    [ -f cfg ] || fail 'This script must be named ~/cfg'
    [ -d .git ] && fail '~/.git already exists'

    # Check git is available
    if ! command -v git >/dev/null; then
        # Attempt to install it if not
        say 'Installing Git'
        if ! (sudo apt-get update && sudo apt-get install -y git); then
            fail 'Git could not be installed'
        fi
    fi

    # Add SSH public key
    say 'Adding SSH public key'
    mkdir -p .ssh
    chmod 700 .ssh
    if ! grep -qs ^git.djm.me .ssh/known_hosts; then
        echo 'git.djm.me ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBLDe4GfSc5+r3DZsL9JHrGyMPrmswdHoOni8BQ2y6yAb6GdXDNtrfrcSy7/a8tfgT1wcUObKyKWVG+tn+foLfPY=' >> .ssh/known_hosts
        echo 'git.djm.me ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPGgKlbrX/hJ+zvs2At5i6HtBdCe5MY9XvmguctjofQs' >> .ssh/known_hosts
        echo 'git.djm.me ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDPZN6vSLWSUMZX6NRsH0WchOshw81YM3H9Wd5V83PdnU+cNQWJ31oml0pwE+0eUR09IjcE+0Rl1LVQBGpYfsWllGC2ZQUkXWnmqwVg73EAkq4Xu7yb27bKaBNLlw5w4cS2CULyEUozEYU0y7j7bSa/zO6rlZykfvEzT9/KGRbGM/SuTazQVkEWVq7gHhLLXWNJWgo5ngx6zArBXE2gHGEtSgowXgqQKrAqzWwm1VZZ3XZYS08jC2bYZ0NtUWPrLHgbs9N/l4/TnOMYiChxYSEc9b5T6oCaY55z8qHrBmKk2x5AyLPs8EsAGbwntYmTMcEgk6U3jctS0yDtZ/XpukFN2VqDVg/rs+04RKdmyNFUBiWlrC5qGnrAwv92mCnQgCF2nLITM6ju1Df6xuKcOrGj53kiKyyjpWsGBwMYV7DUIeTqUjfbDeUbiicj5tIZ8LT15ASXkXQX/ssIW9GmqJUhRqpFb8a7Uqksn22BIQqecucnmmLCx3/ChVXtjjGs96k=' >> .ssh/known_hosts
    fi
    chmod 600 .ssh/known_hosts

    # Download the repository
    say 'Downloading dotfiles repository'
    git init || fail 'Failed to initialise the Git repo'
    git remote add origin 'git@git.djm.me:dave/dotfiles.git' || fail 'Failed to configure the Git remote'
    git fetch --depth=1 origin || fail 'Failed to download the Git repository'

    # Check out the files
    say 'Checking out files'
    git checkout -f origin/main -b main

    # Remove this script
    # (Note: $0 is not set because we 'source' this file)
    say "Removing the 'cfg' bootstrap script"
    rm -f cfg

    # Run any post-install commands, e.g. prepare config file
    say 'Running post-install script'
) && exec ~/.dotfiles/post-install
