#!/usr/bin/env bash
set -euo pipefail

cd

# Support for non-interactive installs (Ansible)
interactive=true
if [[ ${1:-} = '--unattended' ]]; then
    interactive=false
fi

# Reload tmux config
if $interactive && [[ -n ${TMUX:-} ]]; then
    tmux source ~/.tmux.conf
fi

# Create/update the post-merge hook
ln -nsf ../../.dotfiles/post-update .git/hooks/post-merge

# Check permissions on the .ssh/ directory
chmod 700 .ssh
chmod 600 .ssh/* 2>/dev/null || true
chmod 700 .ssh/*.exe 2>/dev/null || true

# Add known host keys for various Git servers
if [[ ! -f .ssh/known_hosts ]]; then
    touch .ssh/known_hosts
    chmod 600 .ssh/known_hosts
fi

if ! grep -q '^github\.com ' .ssh/known_hosts; then
    echo "github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=" >> .ssh/known_hosts
    echo "github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl" >> .ssh/known_hosts
    echo "github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=" >> .ssh/known_hosts
fi

if ! grep -q '^gitlab\.com ' .ssh/known_hosts; then
    echo "gitlab.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBFSMqzJeV9rUzU4kWitGjeR4PWSa29SPqJ1fVkhtj3Hw9xjLVXVYrU9QlYWrOLXBpQ6KWjbjTDTdDkoohFzgbEY=" >> .ssh/known_hosts
    echo "gitlab.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAfuCHKVTjquxvt6CM6tdG4SLp1Btn/nOeHHE5UOzRdf" >> .ssh/known_hosts
    echo "gitlab.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCsj2bNKTBSpIYDEGk9KxsGh3mySTRgMtXL583qmBpzeQ+jqCMRgBqB98u3z++J1sKlXHWfM9dyhSevkMwSbhoR8XIq/U0tCNyokEi/ueaBMCvbcTHhO7FcwzY92WK4Yt0aGROY5qX2UKSeOvuP4D6TPqKF1onrSzH9bx9XUf2lEdWT/ia1NEKjunUqu1xOB/StKDHMoX4/OKyIzuS0q/T1zOATthvasJFoPrAjkohTyaDUz2LN5JoH839hViyEG82yB+MjcFV5MU3N1l1QL3cVUCh93xSaua1N85qivl+siMkPGbO5xR/En4iEY6K2XPASUEMaieWVNTRCtJ4S8H+9" >> .ssh/known_hosts
fi

if ! grep -q '^bitbucket\.org ' .ssh/known_hosts; then
    echo "bitbucket.org ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAubiN81eDcafrgMeLzaFPsw2kNvEcqTKl/VqLat/MaB33pZy0y3rJZtnqwR2qOOvbwKZYKiEO1O6VqNEBxKvJJelCq0dTXWT5pbO2gDXC6h6QDXCaHo6pOHGPUy+YBaGQRGuSusMEASYiWunYN0vCAI8QaXnWMXNMdFP3jHAJH0eDsoiGnLPBlBp4TNm6rYI74nMzgz3B9IikW4WVK+dc8KZJZWYjAuORU3jc1c/NPskD2ASinf8v3xnfXeukU0sJ5N6m5E8VLjObPEO+mN2t/FZTMZLiFqPWc/ALSqnMnnhwrNi2rbfg/rd/IpL8Le3pSBne8+seeFVBoGqzHM9yXw==" >> .ssh/known_hosts
fi

if ! grep -q '^gate\.maths\.ox\.ac\.uk ' .ssh/known_hosts; then
    echo "gate.maths.ox.ac.uk ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIH6XLpixNz9uFyzKi+eAV18QouMmVazXfrs7Mv8rpK7W" >> .ssh/known_hosts
    echo "gate.maths.ox.ac.uk ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBAfAWuO2aHzVWSDEw1uvP+CUB5Q2mfIngVBtHMdLPlrxKw+4XWosMMse7fVeAVuqkWj1XeshMY2CSQc0waj/I4I=" >> .ssh/known_hosts
fi

# Remove old Mercurial local config file if it's empty
if [[ -f .hgrc_local ]] && [[ -z "$(cat .hgrc_local)" ]]; then
    rm -f .hgrc_local
fi

# Move files that used to clutter the home directory
if [[ -d tmp/vim && ! -d .cache/vim ]]; then
    mkdir -p .cache
    mv tmp/vim .cache/vim
    rm -f .cache/vim/.gitkeep
    chmod 700 .cache/vim
    rmdir --ignore-fail-on-non-empty tmp
fi

if [[ -f .vim/.netrwhist && ! -f .cache/vim/.netrwhist ]]; then
    mv .vim/.netrwhist .cache/vim/.netrwhist
fi

if [[ -f .cfg_last_update ]]; then
    if [[ -f .local/dotfiles-last-auto-update ]]; then
        rm .cfg_last_update
    else
        mv .cfg_last_update .local/dotfiles-last-auto-update
    fi
fi

if [[ -f .bash_lastdirectory ]]; then
    if [[ -f .local/bash-last-directory ]]; then
        rm .bash_lastdirectory
    else
        mv .bash_lastdirectory .local/bash-last-directory
    fi
fi

# Add/update remote repositories
if [[ $(git config remote.origin.url) != 'https://github.com/d13r/dotfiles.git' ]]; then
    git remote set-url origin https://github.com/d13r/dotfiles.git
    git remote set-url origin --push git@github.com:d13r/dotfiles.git
fi

# Clean up files that were previously ignored
if [[ -d .vim/bundle ]]; then
    rm -rf .vim/bundle
fi

# Clean up old symlinks (17 May 2023)
if [[ -L .ssh/ssh_auth_sock && ! -e .ssh/ssh_auth_sock ]]; then
    rm .ssh/ssh_auth_sock
fi
