#!/bin/bash
set -o errexit -o nounset -o pipefail

# Make sure Bash gets reloaded no matter what
trap 'exec bash -l' EXIT

PATH="$HOME/.bin:$PATH"

source ~/.bash/ask.sh
source ~/.bash/color.bash

# No need to check for updates today
date +%Y%m%d > ~/.local/dotfiles-last-auto-update

# Run the post-update script too
color lblue 'Running post-update script'
~/.dotfiles/post-update

# Fix WSL permissions (defaults to umask 000)
if is-wsl; then
    color lblue 'Fixing WSL permissions'
    umask 002
    chmod o-w -R "$HOME"

    sudo tee /etc/wsl.conf >/dev/null <<END
[automount]
options = "metadata,umask=0022"
END
fi

# Run Ubuntu setup
if is-ubuntu && is-primary-user && ask "$(color lyellow 'Run Ubuntu setup?')" Y; then
    setup-ubuntu || true
fi

# Reload tmux config
if [[ -n ${TMUX:-} ]]; then
    tmux source ~/.tmux.conf
    tmux display 'Reloaded ~/.tmux.conf'
    tmux move-window -t 1 2>/dev/null # Change from 0 to 1
fi

# Reload Bash
color lblue 'Reloading Bash'
# See EXIT trap above
