#!/bin/bash
set -o errexit -o nounset -o pipefail

repo="${1:-}"
shift

if [[ -z $repo ]]; then
    echo 'Usage: clone <name> [target]' >&2
    exit 2
fi

if [[ $repo == *@* ]] || [[ $repo == *:* ]] || [[ $repo == */*/* ]]; then
    exec git clone "$repo" "$@"
fi

if [[ $repo == alberon/* ]]; then
    exec git clone "git@gitlab.com:alberon/$repo.git" "$@"
fi

if [[ $repo == */* ]]; then
    exec git clone "git@github.com:$repo.git" "$@"
fi

exec git clone "git@git.djm.me:dave/$repo.git" "$@"
