#!/bin/bash
set -o errexit -o nounset -o pipefail

################################################################################
# Copy the last commit from my dotfiles to the Alberon dotfiles.
################################################################################

if [[ ! -d ~/dotfiles/alberon ]]; then
    mkdir -p ~/dotfiles
    git clone git@github.com:alberon/dotfiles.git ~/dotfiles/alberon
    cd ~/dotfiles/alberon
    git remote add dave https://github.com/d13r/dotfiles.git
fi

cd
git push

cd ~/dotfiles/alberon

git checkout master
git pull

git remote set-url dave https://github.com/d13r/dotfiles.git
git fetch dave
git cherry-pick dave/main

git push
