#!/bin/bash
set -o errexit -o nounset -o pipefail

################################################################################
# Copy the last commit from the Alberon dotfiles to my dotfiles.
################################################################################

LCYAN="\e[96m"
RESET="\e[0m"

cd

echo -e "${LCYAN}Checking out main branch...${RESET}"
git checkout main

echo -e "${LCYAN}Pulling remote changes...${RESET}"
git pull

echo -e "${LCYAN}Fetching alberon changes...${RESET}"
git fetch alberon

echo -e "${LCYAN}Cherry picking the latest commit...${RESET}"
git cherry-pick alberon/master

echo -e "${LCYAN}Pushing changes...${RESET}"
git push
