#!/bin/bash
set -o errexit -o nounset -o pipefail

source $HOME/.bash/color.bash

topic=${1:-}

if [[ -z $topic ]]; then
    echo "$(color lwhite Usage:) ref <topic>"
    exit
fi

if [[ ! $topic =~ ^[a-z0-9-]+$ ]]; then
    color lred "Invalid topic name '$topic'"
    exit 1
fi

if curl -f "https://git.djm.me/dave/ref/raw/branch/main/$topic.txt"; then
    echo
    color lblack underline "https://git.djm.me/dave/ref/_edit/main/$topic.txt"
else
    echo
    color lwhite 'Create it?'
    color underline "https://git.djm.me/dave/ref/_new/main?filename=$topic.txt"
fi
